#!/usr/bin/env python3
"""Download the webfonts and self-host them.

Run this once. It writes .woff2 files and fonts.css into website/fonts/, after
which the site makes no third-party requests at all.

    cd tools && python3 fetch_fonts.py

Why self-host:
  - fonts.googleapis.com is a render-blocking stylesheet on the critical path,
    and it has to be fetched before the browser even learns which .woff2 files
    it needs. That is two round trips to somebody else's server before any text
    can paint.
  - Every visitor's IP goes to Google. A German court has already ruled that
    unlawful under GDPR (LG Munich I, 3 O 17493/20), and it is a live question
    under the revised Swiss FADP. This site's audience is almost entirely
    European.
  - Self-hosted fonts are same-origin, so they inherit the immutable cache
    header the rest of website/img/ gets.

The weights below are exactly the ones styles.css uses, checked by reading it.
Note this FIXES two pre-existing bugs: the old Google Fonts URL loaded Inter at
400/500/600 only, so `font-weight: 300` and `font-weight: 700` were being
synthesised by the browser (faux-light and faux-bold, which look wrong at
display sizes). It also stops loading Cormorant italic, which the stylesheet
never uses and no page contains an <em> for.
"""

import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.normpath(os.path.join(HERE, "..", "website", "fonts"))

# family -> (google name, [weights])
WANTED = {
    "cormorant-garamond": ("Cormorant+Garamond", [300, 400]),
    "inter":              ("Inter",              [300, 400, 500, 600, 700]),
}

# The site is EN/FR/DE/IT. latin covers all four; latin-ext is a few KB and
# covers the stray Central European character. Everything else is dropped.
KEEP_SUBSETS = {"latin", "latin-ext"}

# Without a modern browser UA the API serves .ttf instead of .woff2.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def parse_css(css):
    """Yield (subset, weight, style, url, unicode_range) per @font-face block.

    The API emits a `/* latin */` comment immediately before each block, which
    is the only place the subset name appears.

    unicode_range is carried through and is NOT optional. Without it, two
    @font-face rules that share a family, weight and style collide and the last
    one declared wins for the whole character set — so the latin-ext file would
    silently replace the latin one, and ordinary characters would have no
    glyphs and fall back to Georgia.
    """
    for m in re.finditer(r"/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})",
                         css, re.S):
        subset, block = m.group(1), m.group(2)
        weight = re.search(r"font-weight:\s*(\d+)", block)
        style = re.search(r"font-style:\s*(\w+)", block)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        urange = re.search(r"unicode-range:\s*([^;]+);", block)
        if weight and url:
            yield (subset, int(weight.group(1)),
                   style.group(1) if style else "normal", url.group(1),
                   urange.group(1).strip() if urange else None)


def local_name(slug, subset, weight, url_count):
    """Deterministic filename.

    Both families are VARIABLE fonts, so Google serves one .woff2 per subset
    that covers every weight, and returns several @font-face rules pointing at
    the same URL. Naming per weight would store five identical copies of the
    same file. So the weight only appears in the name when a (family, subset)
    genuinely has more than one distinct source file, which is what would
    happen if Google ever went back to static instances.
    """
    if url_count > 1:
        return "%s-%d-%s.woff2" % (slug, weight, subset)
    return "%s-%s.woff2" % (slug, subset)


def main():
    os.makedirs(FONTS, exist_ok=True)
    out, faces, skipped = [], [], 0
    by_url = {}          # source url -> local filename
    manifest = {}        # role -> filename, for the page preloads

    out.append("/* Generated by tools/fetch_fonts.py. Do not edit by hand.\n"
               "   Re-run that script to regenerate. Self-hosted so the site\n"
               "   makes no third-party requests.\n\n"
               "   Both families are variable fonts: one file per subset covers\n"
               "   every weight, which is why several rules below share a src.\n"
               "   unicode-range is what lets the browser pick the right subset\n"
               "   and skip downloading the other one entirely. */\n")

    for slug, (google_name, weights) in WANTED.items():
        spec = "%s:wght@%s" % (google_name, ";".join(str(w) for w in weights))
        api = "https://fonts.googleapis.com/css2?family=%s&display=swap" % spec
        family = google_name.replace("+", " ")
        print("fetching %s ..." % family)
        try:
            css = get(api)
        except Exception as e:
            print("  FAILED: %s" % e, file=sys.stderr)
            print("  Check your network. Nothing has been changed.", file=sys.stderr)
            return 1

        rows = [r for r in parse_css(css)
                if r[0] in KEEP_SUBSETS and r[2] == "normal"]
        skipped += len(list(parse_css(css))) - len(rows)

        # How many distinct source files does each (subset) actually have?
        per_subset = {}
        for subset, weight, _s, url, _u in rows:
            per_subset.setdefault(subset, set()).add(url)

        for subset, weight, _style, url, urange in rows:
            name = local_name(slug, subset, weight, len(per_subset[subset]))
            if url not in by_url:
                # Always re-download rather than skipping files that exist. A
                # partial or zero-byte file from an interrupted run looks
                # present to a naive check but renders as nothing, and the
                # point of this script is that re-running it restores a
                # known-good state.
                data = get(url, binary=True)
                if len(data) < 5000:
                    print("  WARNING: %s came back only %d bytes, that looks "
                          "wrong" % (name, len(data)), file=sys.stderr)
                with open(os.path.join(FONTS, name), "wb") as fh:
                    fh.write(data)
                by_url[url] = name
            name = by_url[url]

            face = ("@font-face {\n"
                    "  font-family: '%s';\n"
                    "  font-style: normal;\n"
                    "  font-weight: %d;\n"
                    "  font-display: swap;\n"
                    "  src: url('%s') format('woff2');\n" % (family, weight, name))
            if urange:
                face += "  unicode-range: %s;\n" % urange
            face += "}\n"
            faces.append(face)

            # The two faces the page head preloads: weight 400, latin subset.
            if weight == 400 and subset == "latin":
                manifest["serif" if slug.startswith("cormorant") else "sans"] = name

    out.extend(faces)
    css_path = os.path.join(FONTS, "fonts.css")
    with open(css_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    # build_site.py reads this to emit the <link rel=preload> tags, so the
    # filenames are never hardcoded in two places.
    if len(manifest) != 2:
        print("  ERROR: could not identify both preload faces: %r" % manifest,
              file=sys.stderr)
        return 1
    with open(os.path.join(FONTS, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write("\n")

    # Delete any .woff2 this run did not write. Renaming the scheme (or
    # dropping a weight) otherwise leaves the old files behind: nothing
    # references them, nothing requests them, and they still get rsynced to the
    # server on every deploy. Silent dead weight is worse than a loud error.
    kept = set(by_url.values())
    removed, freed = 0, 0
    for f in os.listdir(FONTS):
        if f.endswith(".woff2") and f not in kept:
            p = os.path.join(FONTS, f)
            freed += os.path.getsize(p)
            os.remove(p)
            removed += 1
    if removed:
        print("  removed %d stale font file(s), freeing %.1f KB"
              % (removed, freed / 1024.0))

    total = sum(os.path.getsize(os.path.join(FONTS, f)) for f in kept)
    print("\n  %d unique font files, %d faces declared, %d non-latin/italic skipped"
          % (len(by_url), len(faces), skipped))
    print("  %.1f KB of woff2 on disk" % (total / 1024.0))
    print("  preloading: %s, %s" % (manifest["serif"], manifest["sans"]))
    print("\n  Now run:  python3 build_site.py && python3 audit.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
