#!/usr/bin/env bash
#
# Tell Bing, Yandex, Seznam and Naver that the site has changed.
#
# One POST notifies all of them — IndexNow is a shared protocol, and any
# participating engine passes the notification on to the others. Google does
# NOT take part; Google finds changes through Search Console and its own
# crawl. See the checklist in GET-INDEXED.md.
#
# Run it after every deploy:
#     ./deploy/indexing/indexnow-submit.sh
#
# It reads the URL list straight out of website/sitemap.xml, so there is
# nothing to keep in sync by hand.

set -euo pipefail

HOST="bijouduglacier.com"
KEY="c13d276a206e5cd14dbf8988027af48b"
KEY_URL="https://${HOST}/${KEY}.txt"
SITEMAP="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../website" && pwd)/sitemap.xml"

if [[ ! -f "$SITEMAP" ]]; then
  echo "No sitemap at $SITEMAP — run tools/build_site.py first." >&2
  exit 1
fi

# The key file has to be live before anything is accepted. Check it first,
# because the failure is otherwise silent: the endpoint returns 202 and then
# quietly discards the submission.
echo "Checking the key file is live at ${KEY_URL}"
served="$(curl -fsS --max-time 15 "$KEY_URL" 2>/dev/null | tr -d '[:space:]' || true)"
if [[ "$served" != "$KEY" ]]; then
  echo >&2
  echo "The key file is not being served correctly." >&2
  echo "  expected: ${KEY}" >&2
  echo "  got:      ${served:-<nothing — 404 or unreachable>}" >&2
  echo >&2
  echo "It is generated by tools/build_site.py. Rebuild and redeploy, then" >&2
  echo "confirm ${KEY_URL} returns the key as plain text." >&2
  exit 1
fi
echo "  ok"

# Read the URLs out of the sitemap.
#
# Deliberately NOT `mapfile -t`: that is a bash 4 builtin, and macOS still ships
# bash 3.2 (Apple froze it in 2007 rather than move to GPLv3). This loop is the
# portable equivalent and works on both.
# Two separate substitutions rather than `s|</\?loc>||g`. BSD sed, which is what
# macOS ships, has no `\?` operator — that is a GNU extension. There it silently
# matches nothing, the tags survive, and IndexNow rejects the lot with a 400.
URLS=()
while IFS= read -r line; do
  [ -n "$line" ] && URLS+=("$line")
done < <(grep -o '<loc>[^<]*</loc>' "$SITEMAP" \
         | sed -e 's|<loc>||' -e 's|</loc>||' \
         | tr -d '\r')

if [[ ${#URLS[@]} -eq 0 ]]; then
  echo "No <loc> entries found in the sitemap." >&2
  exit 1
fi

# Check what we actually parsed before sending it. IndexNow's answer to a bad
# URL is a flat 400 that tells you nothing about which one or why, so validate
# here where the offending value can be printed.
bad=0
for u in "${URLS[@]}"; do
  case "$u" in
    "https://${HOST}/"*) ;;
    *) echo "  not a valid ${HOST} URL: [${u}]" >&2; bad=$((bad+1)) ;;
  esac
done
if [[ $bad -gt 0 ]]; then
  echo >&2
  echo "${bad} of ${#URLS[@]} parsed entries are not usable URLs, so nothing was" >&2
  echo "submitted. The value is printed in brackets above — if it still has XML" >&2
  echo "tags around it, the sitemap parsing broke rather than the sitemap." >&2
  exit 1
fi

echo "Submitting ${#URLS[@]} URLs"

payload="$(
  printf '{"host":"%s","key":"%s","keyLocation":"%s","urlList":[' "$HOST" "$KEY" "$KEY_URL"
  for i in "${!URLS[@]}"; do
    [[ $i -gt 0 ]] && printf ','
    printf '"%s"' "${URLS[$i]}"
  done
  printf ']}'
)"

code="$(curl -sS -o /tmp/indexnow-response.txt -w '%{http_code}' \
  -X POST "https://api.indexnow.org/IndexNow" \
  -H "Content-Type: application/json; charset=utf-8" \
  --max-time 30 \
  -d "$payload")"

echo "  HTTP ${code}"

case "$code" in
  200|202)
    echo
    echo "Accepted. 202 means queued, which is the normal answer — it is not a"
    echo "promise to index, only confirmation that the engines were told."
    echo "Expect Bing to show movement in a few days."
    ;;
  400) echo "Bad request — the JSON was malformed." >&2; cat /tmp/indexnow-response.txt >&2; exit 1 ;;
  403) echo "Key rejected. The key file is live but does not match what was sent." >&2; exit 1 ;;
  422) echo "URLs rejected — they must all be on ${HOST}." >&2; exit 1 ;;
  429) echo "Rate limited. Wait and try again; do not loop this." >&2; exit 1 ;;
  *)   echo "Unexpected response:" >&2; cat /tmp/indexnow-response.txt >&2; exit 1 ;;
esac
